name: Reppository Events
on: [push, pull_request, issues]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: tests
              run: |
                echo $GITHUB_SHA
                ECHO $GITHUB_REF
            - uses: actions/checkout@v3